<div class="container">
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{{__('content.num')}}</th>
                    <th>{{__('content.name-group')}}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{__('1')}}</td>
                    <td>{{__('content.group-1')}}</td>
                </tr>
                <tr>
                    <td>{{__('2')}}</td>
                    <td>{{__('content.group-2')}}</td>
                </tr>
                <tr>
                    <td>{{__('3')}}</td>
                    <td>{{__('content.group-3')}}</td>
                </tr>
                <tr>
                    <td>{{__('4')}}</td>
                    <td>{{__('content.group-4')}}</td>
                </tr>
                <tr>
                    <td>{{__('5')}}</td>
                    <td>{{__('content.group-5')}}</td>
                </tr>
                <tr>
                    <td>{{__('6')}}</td>
                    <td>{{__('content.group-6')}}</td>
                </tr>
                <tr>
                    <td>{{__('7')}}</td>
                    <td>{{__('content.group-7')}}</td>
                </tr>
                <tr>
                    <td>{{__('8')}}</td>
                    <td>{{__('content.group-8')}}</td>
                </tr>
                <tr>
                    <td>{{__('9')}}</td>
                    <td>{{__('content.group-9')}}</td>
                </tr>
                <tr>
                    <td>{{__('10')}}</td>
                    <td>{{__('content.group-10')}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>